
{*******************************************************}
{                                                       }
{       GraphVision Build Program                       }
{                                                       }
{*******************************************************}

program Build;

uses
   LowGraph,
   EventMan,
   GFonts,
{$IFNDEF DPMI}
   Xms,
{$ENDIF}
   ExtObj,
   Images,
   GrDriver,
   Grav,
   Controls,
   GraMenu,
   GrApp,
   MsgBox,
   GStdDlg,
   GEditors;

begin
end.
